services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8.3.66
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: test_db
      CLICKHOUSE_USER: myuser
      CLICKHOUSE_PASSWORD: mypass
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    restart: unless-stopped
    #    volumes:
    #      - ./data:/var/lib/clickhouse
    #      - ./logs:/var/log/clickhouse-server

    networks:
      - bigdata

networks:
  bigdata:
    external: true